name: Deploy

on:
  workflow_dispatch:
    
jobs:
  call_test_workflow:
    uses: ./.github/workflows/laravel.yml
    with:
      message: "Call testsHello from the caller!"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd ~/www/laravel_source && sh deploy.sh"
