name: Deploy

on:
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: $HOST
          username: $SSH_USERNAME
          port: $SSH_PORT
          key: $SSH_KEY
          script: "cd ~/www/laravel_source && sh deploy.sh"
